### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by NathanBnm** [rickybas/date-countdown#16]
As reported in #13 adding the travis.yml file is not enough. @rickybas you have to register in Travis CI too if you want to use Continuous Integration (highly recommended). See the wiki here https://github.com/elementary/houston/wiki/Continuous-Integration.

**Comment by rickybassom** [comment]
Thanks @NathanBnm. Just got round to doing it. All good now?

**Comment by rickybas** [comment]
Do I need to push another commit to make it work?

**Comment by NathanBnm** [comment]
I don't think so. If it's all good, then the build tests should be launched in every new or updated PR.

**Comment by rickybas** [comment]
Hi @NathanBnm, I have changed a couple of things in travis and it seems to work now?

**Comment by NathanBnm** [comment]
@rickybas you just deleted your message? It looks okay now

**Comment by rickybassom** [comment]
Just wanted to double check something. Do I just need to make a new release now to publish to the app center?

**Comment by NathanBnm** [comment]
There is no need to make a new release for that. The `travis.yml` file purpose is only for the GitHub repo to check build when pushing commits and creating PRs

**Comment by NathanBnm** [comment]
However you can make a new release if you made other changes to your app.

**Comment by rickybassom** [comment]
Thanks!
