### ISSUE TITLE
Change Required for AppCenter: Release Description

### ISSUE THREAD

**Issue by cassidyjames** [rickybas/date-countdown#18]
Thanks for submitting your 0.1.6 update to AppCenter! However, while reviewing the submission, we found an issue that needs to be resolved.

Updates must include accurate [release descriptions](https://docs.elementary.io/develop/appcenter/publishing-updates#release-descriptions). Please detail the user-facing changes in the proper tag.

Once you've made the requested changes, create a new release on GitHub and re-submit it to the [AppCenter Dashboard](https://developer.elementary.io). You can include the 0.1.6 details in the next version's release description since 0.1.6 will have never reached users.

As always, if you have any questions you can reply here.

**Comment by rickybassom** [comment]
Thanks cassidy. Can I remove the latest release and upload a fixed release with the same version tag and fixed release descriptions?

**Comment by rickybassom** [comment]
49552a4cc69cfe90ee6c266567d52b235ad568d6 updated

**Comment by cassidyjames** [comment]
@rickybas AppCenter Dashboard does not support overwriting previously-submitted releases, so it'll need to be bumped e.g. to 0.1.7.

**Comment by rickybassom** [comment]
New release 0.1.7 published with updated appdata
