### ISSUE TITLE
can't add countdown

### ISSUE THREAD

**Issue by ghost** [rickybas/date-countdown#19]
When I try to add a countdown, it shows title and date selection, but the calendar is not well displayed, and when a title and date is selected and click "create", no new countdown is created.
![Screenshot from 2020-06-18 14-10-37](https://user-images.githubusercontent.com/12141382/85056679-a241e300-b16d-11ea-94d1-ce3a0d7c35ef.png)

**Comment by rickybassom** [comment]
Thanks for letting me know. Just released a new version with a fix. Should be out in a few days.
