### ISSUE TITLE
Long non-latin title breaks visual output

### ISSUE THREAD

**Issue by asahnoln** [rickybas/date-countdown#2]
It seems when title is written with non-latin characters, then sometimes the title is being trimmed at wrong symbol position or something, which breaks visual output.

So, this is a normal title in English:
![2017-08-01 16 11 08](https://user-images.githubusercontent.com/2792908/28820749-96982ec8-76d4-11e7-9d17-5c5f0d883896.png)

This is a short title in Russian:
![2017-08-01 16 22 16](https://user-images.githubusercontent.com/2792908/28821043-c57b28a2-76d5-11e7-9ae3-242b203ea728.png)

This is a long title in English. Everything is fine:
![2017-08-01 16 23 08](https://user-images.githubusercontent.com/2792908/28821053-cc121874-76d5-11e7-816a-7b2b6bf7faad.png)

Now this is a long title in Russian, and it breaks the output.
![2017-08-01 16 11 25](https://user-images.githubusercontent.com/2792908/28820753-9b5f85be-76d4-11e7-85c4-9d71ee7791c7.png)

This is a mixed title - with English and Russian characters. It seems to break at the point where a cyrillic character is located.
![2017-08-01 16 12 53](https://user-images.githubusercontent.com/2792908/28820755-9e045858-76d4-11e7-80bb-393467395251.png)

You can copy this to test it out: "Праздник Любви"

**Comment by rickybassom** [comment]
@asahnoln Update published on the AppCenter

**Comment by asahnoln** [comment]
@rickybas Now it works fine, thank you!
