### ISSUE TITLE
Issue with Calendar

### ISSUE THREAD

**Issue by sravanjspro** [rickybas/date-countdown#20]
Hi, 
Thank you for your contribution! 
I am using elementary OS 5.1.5 Hera version.
I found that the calendar was not displaying properly. A screenshot also given below for your understanding. 

![Screenshot from 2020-06-30 23-12-52_modified](https://user-images.githubusercontent.com/44425481/86159110-6fadc800-bb27-11ea-8df9-2b05e8412ad9.png)

Hope you will fix this. Thank you.

**Comment by rickybassom** [comment]
Hi @sravanjsc . That problem should be fixed now. Try updating the app.

**Comment by sravanjspro** [comment]
> Hi @sravanjsc . That problem should be fixed now. Try updating the app.

Thank you.
