### ISSUE TITLE
could you make a flatpak for date-countdown?

### ISSUE THREAD

**Issue by ghost** [rickybas/date-countdown#7]
Hi, I really appreciate your work , is a good application
but i don't use elementary OS
could you make a flatpak for date-countdown?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by rickybassom** [comment]
I will look into it.

**Comment by rickybassom** [comment]
5a84382183b37e31a39fb47d097d8196f3d2112a
b56d71d80fa6cc5104a1aa9f99199a12d9e88af9
